version: '3.9'

services:

 api:
  container_name: api
  build: ./back-end/api
  env_file:
    - .env
  ports:
    - 8000:8000
  volumes:
    - ./back-end/api:/usr/src/app


  db:
    build: ./back-end/db
    container_name: db
    env_file:
      - .env
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./back-end/db/data:/var/lib/postgresql/data      

  # dbt:
  #   container_name: dbt
  #   build: ./back-end/flows/dbt
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env
  #   ports:
  #     - 8080:8080      
  #   restart: always
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ./back-end/flows/dbt:/usr/src/app/dbt

  # flows:
  #   container_name: flows
  #   build: ./back-end/flows
  #   env_file:
  #     - .env
  #   ports:
  #     - 8050:8050
  #   restart: always
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ./back-end/flows:/usr/src/app

  # prefect:
  #   container_name: prefect
  #   build: ./orc
  #   env_file:
  #     - .env
  #   restart: always
  #   stdin_open: true
  #   tty: true    
  #   volumes:
  #     - ./orc:/app