version: '3.9'

services:

  api:
    container_name: api
    build: ./back-end/api
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./back-end/api:/usr/src/app

  db:
    build: ./back-end/db
    container_name: db
    env_file:
      - .env
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./back-end/db/data:/var/lib/postgresql/data      
